# modules/omp.nix
#
# Installs the oh-my-pi (omp) coding agent and writes its configuration
# files for each user listed in services.aiAgent.users.
#
# omp is sourced from numtide/llm-agents.nix via the `llmAgentsPkgs` module
# argument injected by flake.nix.  This gives us a maintained derivation with
# daily updates and pre-built binaries from the Numtide cache, eliminating
# the need for a custom pkgs/omp.nix derivation.
#
# Files written per user:
#   ~/.omp/agent/models.yml    — provider + model routing configuration
#   ~/.omp/agent/settings.json — omp runtime settings (theme, compaction, etc.)
#   ~/.omp/agent/extensions/memory-hook/index.ts
#                              — extension that injects Qdrant search results
#                                into context before each session starts
#
# The extension is compiled by omp on first run (it calls `bun build`
# automatically on extension load).  No separate build step is needed.
#
# References for omp config schema:
#   https://pi.dev/docs/latest/models
#   https://pi.dev/docs/latest/configuration
#   https://pi.dev/docs/latest/extensions
{
  config,
  pkgs,
  lib,
  ...
}:

let
  cfg = config.services.aiAgent;
  memCfg = cfg.memory;
  agCfg = cfg.agent;

  # omp package — set by the user via services.aiAgent.ompPackage.
  # Recommended source: inputs.llm-agents.packages.${system}.omp
  ompPkg = cfg.ompPackage;

  # ── models.yml ────────────────────────────────────────────────────────────
  # Defines two custom providers:
  #   "orchestrator" → MiniMax on your cluster (main reasoning model)
  #   "coding-agent" → Qwen on a second set of nodes (fast implementation)
  #
  # modelRoles lets omp automatically use the right model for each task:
  #   default  → orchestrator (MiniMax)
  #   subagent → coding-agent (Qwen)
  #
  # compat flags handle llama-server's partial OpenAI API compliance:
  #   supportsDeveloperRole    = false : llama-server uses "system", not "developer"
  #   supportsReasoningEffort  = false : llama-server doesn't implement this param
  #   supportsUsageInStreaming = false : usage tokens come only at stream end
  #
  # See https://pi.dev/docs/latest/models#compat for full compat reference.
  modelsYml = user: ''
    # omp models.yml — generated by NixOS module services.aiAgent
    # Edit services.aiAgent.orchestratorUrl/codingAgentUrl in configuration.nix
    # to change backend endpoints without touching this file.

    providers:
      orchestrator:
        baseUrl: "${cfg.orchestratorUrl}/v1"
        api: openai-completions
        # llama-server ignores the API key; any non-empty string works.
        apiKey: "nixos-managed"
        compat:
          supportsDeveloperRole: false
          supportsReasoningEffort: false
          supportsUsageInStreaming: false
        models:
          - id: "${cfg.orchestratorModel}"
            name: "Orchestrator (${cfg.orchestratorModel})"
            # Declare large context window; llama-server was started with --ctx-size.
            contextWindow: 65536

      coding-agent:
        baseUrl: "${cfg.codingAgentUrl}/v1"
        api: openai-completions
        apiKey: "nixos-managed"
        compat:
          supportsDeveloperRole: false
          supportsReasoningEffort: false
          supportsUsageInStreaming: false
        models:
          - id: "${cfg.codingAgentModel}"
            name: "Coding Agent (${cfg.codingAgentModel})"
            contextWindow: 32768

    # Model role routing:
    # omp selects a model based on the role of the current session.
    #   default  → used for the top-level conversation (MiniMax)
    #   subagent → used when MiniMax delegates a coding task via the task tool
    modelRoles:
      default:
        provider: orchestrator
        model: "${cfg.orchestratorModel}"
      subagent:
        provider: coding-agent
        model: "${cfg.codingAgentModel}"

    # Fallback chains: if the primary provider fails (e.g. the node is down),
    # fall through to the other backend.  Both run llama.cpp so either can
    # handle either workload in a pinch.
    retry:
      fallbackChains:
        default:
          - provider: orchestrator
            model: "${cfg.orchestratorModel}"
          - provider: coding-agent
            model: "${cfg.codingAgentModel}"
  '';

  # ── settings.json ─────────────────────────────────────────────────────────
  # Core omp runtime settings.
  # contextWindowFraction controls when compaction triggers.
  # extraSettings lets the user add arbitrary keys (theme, keybindings, etc.)
  settingsJson =
    user:
    builtins.toJSON (
      lib.recursiveUpdate {
        # Compact (summarise) the conversation when this fraction of the context
        # window is consumed.  Leaves room for injected memory snippets.
        "context.compactThreshold" = agCfg.contextWindowFraction;

        # How many prior session summaries to include on resume.
        "context.sessionSummaryDepth" = 3;

        # Subagent task tool: spawn Qwen for coding tasks automatically.
        # The model role "subagent" defined in models.yml is used.
        "tasks.enabled" = true;
        "tasks.maxConcurrent" = 2;

        # Memory extension: inject Qdrant results before each session.
        # The extension itself is written separately (see below).
        "extensions.enabled" = true;

        # LSP is on by default; point to language servers installed on your system.
        "lsp.enabled" = true;

        # Session persistence: JSONL files in ~/.omp/agent/sessions/
        # (this is omp's default; listed here for clarity)
        "sessions.dir" = "~/.omp/agent/sessions";

        # Disable omp's built-in telemetry (it's opt-in anyway).
        "telemetry.enabled" = false;
      } agCfg.extraSettings
    );

  # ── Memory injection extension ────────────────────────────────────────────
  # A small TypeScript extension that hooks before_agent_start to:
  #   1. Query Qdrant for the top-K most relevant code chunks
  #      using the user's first message as the query.
  #   2. Prepend the results as a synthetic "context" message.
  #
  # This extension uses omp's extension API:
  #   https://pi.dev/docs/latest/extensions
  #
  # It runs in the same Bun process as omp (no subprocess).
  # The qdrant-client npm package is fetched by bun on first load.
  memoryExtension = ''
    // ~/.omp/agent/extensions/memory-hook/index.ts
    // Generated by NixOS module services.aiAgent — do not edit by hand.
    //
    // Injects relevant codebase snippets from Qdrant into context before
    // each agent session starts.  Uses the session's first user message
    // as the embedding query.
    //
    // Dependencies are resolved by bun at runtime from the global bun store.
    // Run `bun add @qdrant/js-client-rest fastembed` once if needed.

    import type { Extension, AgentSession } from "@oh-my-pi/pi-coding-agent";
    import { QdrantClient } from "@qdrant/js-client-rest";

    const QDRANT_URL   = "http://127.0.0.1:${toString memCfg.qdrantHttpPort}";
    const COLLECTION   = "codebase";
    const TOP_K        = ${toString agCfg.memorySnippets};
    const EMBED_URL    = QDRANT_URL;  // fastembed runs server-side; we use Qdrant's built-in

    const client = new QdrantClient({ url: QDRANT_URL });

    // Helper: embed a query string using Qdrant's local fastembed integration.
    // (Qdrant >=1.10 supports server-side embedding via the named vectors API.)
    // If your Qdrant version is older, swap this for a direct fastembed call.
    async function queryMemory(queryText: string): Promise<string[]> {
      try {
        const results = await client.query(COLLECTION, {
          query:        queryText,
          using:        "text",         // named vector configured in collection
          limit:        TOP_K,
          with_payload: true,
        });
        return results.points
          .filter(p => p.payload?.preview)
          .map(p => {
            const file    = p.payload!.file as string;
            const preview = p.payload!.preview as string;
            return "// " + file + "\n" + preview;
          });
      } catch (err) {
        // Qdrant unavailable (e.g. service not yet started) — silently skip.
        console.warn("[memory-hook] Qdrant query failed:", (err as Error).message);
        return [];
      }
    }

    const extension: Extension = {
      name: "memory-hook",

      // Hook: called once, immediately before the agent loop starts.
      // We intercept the first user message to use as the query.
      hooks: {
        before_agent_start: async (session: AgentSession) => {
          const messages = session.getMessages();
          const firstUser = messages.find(m => m.role === "user");
          if (!firstUser) return;

          const query    = typeof firstUser.content === "string"
            ? firstUser.content
            : (firstUser.content as Array<{type:string;text?:string}>)
                .filter(b => b.type === "text")
                .map(b => b.text ?? "")
                .join(" ");

          if (!query.trim()) return;

          const snippets = await queryMemory(query);
          if (snippets.length === 0) return;

          const contextBlock = [
            "## Relevant codebase context (from vector memory)",
            "",
            ...snippets.map((s, i) => "### Snippet " + (i + 1) + "\n```\n" + s + "\n```"),
          ].join("\n");

          // Inject as a system context message before the user's message.
          // omp's context hook receives the full message list and can rewrite it.
          session.prependSystemContext(contextBlock);
        },
      },
    };

    export default extension;
  '';

in
{
  config = lib.mkIf cfg.enable {

    # ── Install omp system-wide ───────────────────────────────────────────
    environment.systemPackages = [
      ompPkg
      pkgs.bun
    ];

    # ── Write per-user config files ───────────────────────────────────────
    # We use systemd.user services (oneshot) to write config files into
    # each user's home directory at login.  This avoids home-manager
    # as a hard dependency while still being declarative.
    #
    # Files are written only if they've changed (checked via sha256 comparison
    # in the ExecStart script) so the service is idempotent.
    systemd.services = lib.mkMerge (
      map (user: {
        "ai-agent-config-${user}" = {
          description = "Write ai-agent config files for ${user}";
          wantedBy = [ "multi-user.target" ];
          before = [ "display-manager.service" ];

          serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
            User = user;
            Group = config.users.users.${user}.group or "users";
          };

          script =
            let
              # Write each config file atomically (write to tmp, then mv).
              modelsContent = modelsYml user;
              settingsContent = settingsJson user;
              extensionContent = memoryExtension;
            in
            ''
              set -euo pipefail

              OMP_DIR="$HOME/.omp/agent"
              EXT_DIR="$OMP_DIR/extensions/memory-hook"

              mkdir -p "$OMP_DIR" "$EXT_DIR"

              # models.yml
              NEW_MODELS=${lib.escapeShellArg modelsContent}
              if [ ! -f "$OMP_DIR/models.yml" ] || \
                 [ "$(sha256sum "$OMP_DIR/models.yml" | cut -d' ' -f1)" != \
                   "$(echo "$NEW_MODELS" | sha256sum | cut -d' ' -f1)" ]; then
                printf '%s' "$NEW_MODELS" > "$OMP_DIR/models.yml.tmp"
                mv "$OMP_DIR/models.yml.tmp" "$OMP_DIR/models.yml"
                echo "ai-agent: wrote models.yml"
              fi

              # settings.json
              NEW_SETTINGS=${lib.escapeShellArg settingsContent}
              if [ ! -f "$OMP_DIR/settings.json" ] || \
                 [ "$(sha256sum "$OMP_DIR/settings.json" | cut -d' ' -f1)" != \
                   "$(echo "$NEW_SETTINGS" | sha256sum | cut -d' ' -f1)" ]; then
                printf '%s' "$NEW_SETTINGS" > "$OMP_DIR/settings.json.tmp"
                mv "$OMP_DIR/settings.json.tmp" "$OMP_DIR/settings.json"
                echo "ai-agent: wrote settings.json"
              fi

              # memory extension
              NEW_EXT=${lib.escapeShellArg extensionContent}
              if [ ! -f "$EXT_DIR/index.ts" ] || \
                 [ "$(sha256sum "$EXT_DIR/index.ts" | cut -d' ' -f1)" != \
                   "$(echo "$NEW_EXT" | sha256sum | cut -d' ' -f1)" ]; then
                printf '%s' "$NEW_EXT" > "$EXT_DIR/index.ts.tmp"
                mv "$EXT_DIR/index.ts.tmp" "$EXT_DIR/index.ts"
                echo "ai-agent: wrote memory-hook extension"
              fi

              # Write a minimal package.json for the extension so omp/bun can
              # resolve its @qdrant/js-client-rest import.
              cat > "$EXT_DIR/package.json" <<'EOF'
              {
                "name": "memory-hook",
                "version": "1.0.0",
                "private": true,
                "dependencies": {
                  "@qdrant/js-client-rest": "^1.9.0"
                }
              }
              EOF

              # Pre-install the extension's JS dependency so omp starts without
              # needing network access on first run.
              if [ ! -d "$EXT_DIR/node_modules/@qdrant" ]; then
                echo "ai-agent: installing extension dependencies..."
                cd "$EXT_DIR"
                ${pkgs.bun}/bin/bun install --production 2>&1 || \
                  echo "ai-agent: bun install failed (no network?); will retry on next login"
              fi
            '';
        };
      }) cfg.users
    );

    # ── firewall: keep Qdrant localhost-only (no rules needed) ───────────
    # Qdrant is bound to 127.0.0.1 by the vector-memory module.
    # No firewall holes needed.  If you ever want LAN access, add:
    #   networking.firewall.allowedTCPPorts = [ memCfg.qdrantHttpPort ];
  };
}
